os:
  - linux
  - osx
# install deno v0.2.0
before_script: curl -s https://raw.githubusercontent.com/chiefbiiko/deno-bash-installer/master/install.sh | sudo bash -s v0.2.0
# run da test, travis requires sudo when writing
script: sudo deno -D --allow-write --allow-net --allow-env --allow-run ./install.ts